service: lambda-tableau

provider:
  name: aws
  runtime: python3.7
  logRetentionInDays: 14
  role: ${env:TABLEAU_ROLE}
  
plugins:
  - serverless-python-requirements

functions:
  queue_extracts:
    handler: queue_extracts.handler
    events:
      - http:
          path: queue_extracts
          method: put
          integration: lambda-proxy
